inputs:
  port:
    description: 'Port for node appliaction to run'
    defaul: 1010
  environment:
    description: 'Eviroment for node application'
    default: 'DEV'
runs:
  using: "composite"
  steps:
    - name: ... Deploying to ${{inputs.environment}} ...
      working-directory: source
      run: echo Deploying to ${{inputs.environment}}
      shell: cmd

    - name: ... Cloning repository ...
      uses: actions/checkout@v3.5.2
      with:
        repository: ReinisVelmeris/python-greetings
        ref: main
        path: source

    - name: ... Delete greetings app ...
      working-directory: source
      run: pm2 delete greetings-app-${{inputs.environment}} & set "errorlevel=0"
      shell: cmd

    - name: ... Start greetings app ...
      working-directory: source
      run: pm2 start app.py --name greetings-app-${{inputs.environment}} -- --port ${{ inputs.port}}
      shell: cmd

    - name: ... Test if service is running ...
      working-directory: source
      run: curl -X GET http://127.0.0.1:7001/greetings
      shell: cmd