inputs:
  port:
    description: 'Port for node appliaction to run'
    defaul: 1010
  environment:
    description: 'Eviroment for node application'
    default: 'DEV'
runs:
  using: "composite"
  steps:
    - name: ... deploy success ...
      working-directory: source\python-greetings
      run: echo Deploying to ${{inputs.environment}}

    - name: ... Cloning repository ...
      uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        ref: main
        path: source

    - name: ... Delete greetings app ...
      working-directory: source\python-greetings
      run: pm2 delete greetings-app-${{inputs.environment}} & set "errorlevel=0"

    - name: ... Start greetings app ...
      working-directory: source\python-greetings
      run: pm2 start app.py --name greetings-app-${{inputs.environment}} -- --port ${{ inputs.port}}